Repository GeekbrainTeam/StockTipsApp, pull requests merged in 2022-07, with the labels that each got.

#7 GB 5 add parser json (in work)
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  core/build.gradle
  core/src/main/AndroidManifest.xml
  core/src/main/java/com/amk/core/api/CreateMoexCandle.kt
  core/src/main/java/com/amk/core/entity/Company.kt
  core/src/main/java/com/amk/core/entity/company/MoexCandleCursor.kt
  core/src/main/java/com/amk/core/entity/company/MoexData.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/History.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/Metadata.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/MetadataX.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/ADMITTEDQUOTE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/ADMITTEDVALUE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/BOARDID.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/CLOSE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/HIGH.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/HistoryCursor.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/INDEX.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/LEGALCLOSEPRICE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/LOW.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/MARKETPRICE2.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/MARKETPRICE3.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/MARKETPRICE3TRADESVALUE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/MP2VALTRD.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/NUMTRADES.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/OPEN.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/PAGESIZE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/SECID.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/SHORTNAME.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/TOTAL.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/TRADEDATE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/TRADINGSESSION.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/VALUE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/VOLUME.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/WAPRICE.kt
  core/src/main/java/com/amk/core/entity/moex_model/json/metadata/WAVAL.kt
  core/src/main/java/com/amk/core/repository/Repository.kt
  core/src/main/java/com/amk/core/repository/View.kt
  core/src/main/java/com/amk/core/retrofit/GsonCompaniesPageResponseStructure.kt
  core/src/main/java/com/amk/core/retrofit/MoexApiImpl.kt
  core/src/main/java/com/amk/core/retrofit/MoexApiService.kt
  core/src/main/java/com/amk/core/utils/DateUtil.kt
Labels: feature

#9 Feature/gb 8 delete unnecessary files
  core/src/main/java/com/amk/core/api/MoexApi.kt
  core/src/main/java/com/amk/core/api/MoexServiceNetwork.kt
  core/src/main/java/com/amk/core/api/MoexServiceNetworkImpl.kt
  core/src/main/java/com/amk/core/api/RetrofitModule.kt
  core/src/main/java/com/amk/core/entity/company/MoexCompanyRaw.kt
Labels: feature

#11 Fix/GB 11 grale fix
  .gitignore
  app/build.gradle
Labels: bug

#14 Fix/GB-39 develop add gradle
  app/build.gradle
Labels: bug

#25 Fab behavior improvement.
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  list-companies/src/main/res/layout/fragment_list_company.xml
Labels: bug

#24 Feature/GB 43 companies list viewmodel
  core/src/main/java/com/amk/core/repository/NetworkRepository.kt
  core/src/main/java/com/amk/core/repository/Repository.kt
  core/src/main/java/com/amk/core/repository/View.kt
  core/src/main/java/com/amk/core/retrofit/MoexApiService.kt
  core/src/main/java/com/amk/core/utils/DateUtil.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  list-companies/src/main/java/com/amk/mylibrary/viewmodel/CompaniesListViewModel.kt
Labels: feature

#29 SB-31 Add view with candles.
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/AxisYView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/BaseView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/ChartValue.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/ColorBody.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/ColorCandle.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/Paints.kt
  company/src/main/java/com/amk/company/ui/candlechart/CandlestickView.kt
  company/src/main/res/layout/fragment_company.xml
  company/src/main/res/layout/view_candlestick.xml
  company/src/main/res/values/strings.xml
  core/src/main/java/com/amk/core/utils/DateUtil.kt
Labels: feature

#30 Fix after merge.
  company/src/main/java/com/amk/company/ui/baseviewchart/AxisYView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/BaseView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/ColorBody.kt
  company/src/main/java/com/amk/company/ui/candlechart/CandlestickView.kt
  list-companies/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesHolder.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/DialogSorting.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
Labels: bug

#33 GB-51 Add Koin.
  app/src/main/java/com/amk/stocktipsapp/App.kt
  app/src/main/java/com/amk/stocktipsapp/di/ViewModelModule.kt
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  company/src/main/java/com/amk/company/viewmodel/CompanyViewModel.kt
  core/build.gradle
  core/src/main/java/com/amk/core/di/AppModule.kt
  core/src/main/java/com/amk/core/di/RepositoryModule.kt
  core/src/main/java/com/amk/core/di/ViewModelModule.kt
  core/src/main/java/com/amk/core/repository/CacheRepository.kt
  core/src/main/java/com/amk/core/repository/NetworkRepository.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
  list-companies/build.gradle
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  list-companies/src/main/java/com/amk/mylibrary/viewmodel/CompaniesListViewModel.kt
Labels: feature

#35 GB-55 Refactoring.
  company/src/main/java/com/amk/company/presentation/CompanyViewModel.kt
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  core/src/main/java/com/amk/core/repository/CacheRepository.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompany.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
  core/src/main/java/com/amk/core/ui/BaseFragment.kt
  core/src/main/java/com/amk/core/utils/Const.kt
  list-companies/src/main/java/com/amk/mylibrary/interactors/ListCompanyFragmentState.kt
  list-companies/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  list-companies/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/DialogSorting.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  list-companies/src/main/java/com/amk/mylibrary/utils/Const.kt
  list-companies/src/main/java/com/amk/mylibrary/utils/StatesCompanyList.kt
  list-companies/src/main/java/com/amk/mylibrary/viewmodel/CompaniesListViewModel.kt
Labels: feature

#39 Refactoring. Part 3.
  .idea/gradle.xml
  app/build.gradle
  companiesList/.gitignore
  companiesList/build.gradle
  companiesList/consumer-rules.pro
  companiesList/proguard-rules.pro
  companiesList/src/androidTest/java/com/amk/mylibrary/ExampleInstrumentedTest.kt
  companiesList/src/main/AndroidManifest.xml
  companiesList/src/main/java/com/amk/mylibrary/interactors/ListCompanyFragmentState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/RecyclerViewState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesAdapter.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesHolder.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/DialogSorting.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  companiesList/src/main/res/anim/from_bottom_animation.xml
  companiesList/src/main/res/anim/to_bottom_animation.xml
  companiesList/src/main/res/color/color_selector.xml
  companiesList/src/main/res/layout/dialog_filter.xml
  companiesList/src/main/res/layout/dialog_sort.xml
  companiesList/src/main/res/layout/fragment_list_company.xml
  companiesList/src/main/res/layout/item_company.xml
  companiesList/src/main/res/values/strings.xml
  companiesList/src/test/java/com/amk/mylibrary/ExampleUnitTest.kt
  settings.gradle
Labels: feature

#38 GB 23 save favorites
  companiesList/src/main/java/com/amk/mylibrary/interactors/RecyclerViewState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesAdapter.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesHolder.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  core/src/main/java/com/amk/core/db/CashDao.kt
  core/src/main/java/com/amk/core/repository/CacheRepository.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompany.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
  list-companies/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  list-companies/src/main/java/com/amk/mylibrary/viewmodel/CompaniesListViewModel.kt
Labels: feature

#41 Refactoring.
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/BaseView.kt
Labels: feature

#43 Gb-57 Add chart three line break.
  .idea/gradle.xml
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/AxisYView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/BaseView.kt
  company/src/main/java/com/amk/company/ui/baseviewchart/ColorBody.kt
  company/src/main/java/com/amk/company/ui/linechart/LineChart.kt
  company/src/main/java/com/amk/company/ui/threelinebreak/ThreeLineBreakView.kt
  company/src/main/res/drawable/icon.xml
  company/src/main/res/drawable/icon_candlestick_chart.png
  company/src/main/res/drawable/icon_three_line_break_chart.png
  company/src/main/res/layout/fragment_company.xml
  company/src/main/res/layout/view_linechart.xml
  company/src/main/res/layout/view_threelinebreak.xml
  core/src/main/java/com/amk/core/entity/ColorCandle.kt
  core/src/main/java/com/amk/core/entity/ThreeLineBreakCompany.kt
  core/src/main/java/com/amk/core/interactors/ThreeLineBreakCompanyFactory.kt
Labels: feature

#49 Add favorite screen. Add candle chart.
  .idea/gradle.xml
  .idea/misc.xml
  favorite/src/main/java/ru/amk/favorite/interactors/RecyclerViewFavoriteState.kt
  favorite/src/main/java/ru/amk/favorite/interactors/StatesFavoriteInteractor.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesAdapter.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesHolder.kt
  favorite/src/main/java/ru/amk/favorite/ui/FavoriteFragment.kt
  favorite/src/main/java/ru/amk/favorite/ui/baseviewchart/AxisYViewFavorite.kt
  favorite/src/main/java/ru/amk/favorite/ui/baseviewchart/BaseViewFavorite.kt
  favorite/src/main/java/ru/amk/favorite/ui/baseviewchart/ChartValue.kt
  favorite/src/main/java/ru/amk/favorite/ui/candlechart/CandlestickViewFavorite.kt
  favorite/src/main/res/layout/fragment_favorite.xml
  favorite/src/main/res/layout/item_favorite.xml
Labels: bug, feature

#52 Fix after merge branch add favorite.
  companiesList/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompany.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesAdapter.kt
Labels: bug

#51 GB-63 Remove jump to up when add or delete favorite.
  companiesList/src/main/java/com/amk/mylibrary/interactors/RecyclerViewState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesAdapter.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
Labels: bug

#54 GB-65 Fix bug with add favorite.
  companiesList/src/main/java/com/amk/mylibrary/interactors/ListCompanyFragmentState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/RecyclerViewState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesAdapter.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/adapter/ListCompaniesHolder.kt
  core/src/main/java/com/amk/core/db/CashDao.kt
  core/src/main/java/com/amk/core/db/DataBaseCacheCompany.kt
  core/src/main/java/com/amk/core/di/RepositoryModule.kt
  core/src/main/java/com/amk/core/entity/EntityFavoriteCompany.kt
  core/src/main/java/com/amk/core/entity/FaforiteFragmentState.kt
  core/src/main/java/com/amk/core/entity/FavoriteCompany.kt
  core/src/main/java/com/amk/core/entity/FavoriteCompanyShow.kt
  core/src/main/java/com/amk/core/repository/CacheRepository.kt
  core/src/main/java/com/amk/core/repository/CacheRepositoryRoom.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompany.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
  favorite/src/main/java/ru/amk/favorite/interactors/FaforiteFragmentState.kt
  favorite/src/main/java/ru/amk/favorite/interactors/RecyclerViewFavoriteState.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesAdapter.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesHolder.kt
Labels: bug

#57 GB-69 Refactoring repository.
  app/src/main/java/com/amk/stocktipsapp/UI/FabBehavior.kt
  core/src/main/java/com/amk/core/interactors/FavoriteFactory.kt
  core/src/main/java/com/amk/core/repository/RepositoryCompanyImpl.kt
Labels: feature

#59 GB-75 Add splash screen.
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/amk/stocktipsapp/SplashScreenActivity.kt
  app/src/main/java/com/amk/stocktipsapp/ui/MainActivity.kt
  app/src/main/res/anim/anim_gone.xml
  app/src/main/res/anim/anim_gone_activity.xml
  app/src/main/res/anim/anim_show.xml
  app/src/main/res/drawable/splash_first.png
  app/src/main/res/drawable/splash_second.png
  app/src/main/res/layout-v26/splash_scene_second.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/splash_scene_first.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#61 GB 79 logo in favorites
  core/src/main/assets/logos/DVEC.png
  favorite/src/main/java/ru/amk/favorite/interactors/RecyclerViewFavoriteState.kt
  favorite/src/main/java/ru/amk/favorite/interactors/StatesFavoriteInteractor.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesAdapter.kt
  favorite/src/main/java/ru/amk/favorite/presentation/adapter/FavoriteCompaniesHolder.kt
  favorite/src/main/java/ru/amk/favorite/ui/FavoriteFragment.kt
  favorite/src/main/res/layout/item_favorite.xml
Labels: feature

#65 GB 85 add indicators
  company/src/main/java/com/amk/company/ui/CompanyFragment.kt
  company/src/main/res/layout/fragment_company.xml
  core/src/main/java/com/amk/core/utils/Indicators.kt
Labels: feature

#66 GB 87 DaysListToWeeksAndMonthsList.kt
  core/src/main/java/com/amk/core/utils/DateUtil.kt
  core/src/main/java/com/amk/core/utils/DaysListToWeeksAndMonthsList.kt
Labels: feature

#67 GB -89 Fix logic offset list companies.
  .idea/misc.xml
  app/src/main/res/drawable/splash_first.png
  app/src/main/res/drawable/splash_second.png
  companiesList/src/main/java/com/amk/mylibrary/interactors/RecyclerViewState.kt
  companiesList/src/main/java/com/amk/mylibrary/interactors/StatesCompanyListInteractor.kt
  companiesList/src/main/java/com/amk/mylibrary/presentation/CompaniesListViewModel.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  companiesList/src/main/res/anim/from_bottom_animation.xml
  companiesList/src/main/res/anim/to_bottom_animation.xml
Labels: bug

#68 GB-91 Add show current sorting on sorting dialog.
  companiesList/src/main/java/com/amk/mylibrary/ui/DialogSorting.kt
  companiesList/src/main/java/com/amk/mylibrary/ui/ListCompanyFragment.kt
  companiesList/src/main/res/layout/dialog_sort.xml
Labels: feature
